version: '3.8'
services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: simplechat
      POSTGRES_PASSWORD: simplechatpass
      POSTGRES_DB: simplechat
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
  app:
    build: .
    command: sh -c "npm install && npm run dev"
    volumes:
      - ./:/app
    ports:
      - '3000:3000'
    environment:
      DATABASE_URL: postgres://simplechat:simplechatpass@db:5432/simplechat
    depends_on:
      - db
volumes:
  db_data:
